### ISSUE TITLE
Add a License file

### ISSUE THREAD

**Issue by aliyesar** [sudeepmahato16/airbnb-clone#13]
Dear Sudeep,

I couldn't see the License doc for this repo. Could you please let me know if there is a license for this repo? I am wondering if this is available as a free open source repo for a commercial use?

Thank you,
Aliye

**Comment by sudeepmahato16** [comment]
Dear Aliye,

Thank you for letting me know about that. My bad for not having it in there, to begin with. I've now added a License file to the repo. The whole thing is under the MIT License, so you can use it however you want, even for commercial stuff.

Just take a look at the full license text in the LICENSE file in the repo if you want more info. Thanks for pointing this out and for your understanding. You're the best!

Take care,
Sudeep
