### ISSUE TITLE
Slight deployment/forking issue

### ISSUE THREAD

**Issue by thisismyamazingusername** [sudeepmahato16/airbnb-clone#14]
Hi, firstly, thanks for making this publicly available. As a student, it's an honor to learn from this! 

When I forked this repo, adding env variables to vercel (assuming you also used edgestore.dev, used google oauth/cloud console), I came across this error and was not sure if you also came across this/how you fixed this!

After I modified Map.tsx and ListingInfo.tsx to **(see below)** : I got this error: "Collecting page data  ...th [EdgeStoreCredentialsError]: Missing EDGE_STORE_ACCESS_KEY or EDGE_STORE_SECRET_KEY. 
This can happen if you are trying to import something related to the backend of Edge Store in a client component." Not sure how to resolve this because I also added .env.local file as well...

If not no worries, any advice would be helpful, but thanks again!

<img width="1001" alt="image" src="https://github.com/sudeepmahato16/airbnb-clone/assets/111548413/8e227236-bb16-4dfa-8a8d-af8412db647b">

Changed Map.tsx to -- 
import React from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import { MapContainer, Marker, TileLayer } from "react-leaflet";

// Set default icon URLs
import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
import marketIcon from "leaflet/dist/images/marker-icon.png";
import markerShadow from "leaflet/dist/images/marker-shadow.png";

// Set default icon URLs
L.Marker.prototype.options.icon = L.icon({
  iconUrl: marketIcon.src as string,
  iconRetinaUrl: markerIcon2x.src as string,
  shadowUrl: markerShadow.src as string,
});

interface MapProps {
  center?: L.LatLngExpression;
}

const Map: React.FC<MapProps> = ({ center }) => {
  return (
    <MapContainer
      center={center || [52, -0.09]}
      zoom={center ? 4 : 2}
      scrollWheelZoom={false}
      className={`h-full rounded-lg`}
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      {center && <Marker position={center} />}
    </MapContainer>
  );
};

export default Map;
,, 
______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______ ______
Changed ListingInfo.tsx to-- 
import React from "react";
import dynamic from "next/dynamic";

import Avatar from "@/components/Avatar";
import ListingCategory from "./ListingCategory";
import { Category } from "@/types";

interface ListingInfoProps {
  user: {
    image: string | null;
    name: string | null;
  };
  description: string;
  guestCount: number;
  roomCount: number;
  bathroomCount: number;
  category: Category | undefined;
  latlng: number[];
}

const Map = dynamic(() => import("@/components/Map"), {
  ssr: false,
});

const ListingInfo: React.FC<ListingInfoProps> = ({
  user,
  description,
  guestCount,
  roomCount,
  bathroomCount,
  category,
  latlng,
}) => {
  return (
    <div className="col-span-4 flex flex-col gap-8">
      <div className="flex flex-col gap-2">
        <div className="text-[16px] font-semibold flex flex-row items-center gap-2">
          <span className="mr-1">Hosted by</span> <Avatar src={user?.image} />
          <span> {user?.name}</span>
        </div>
        <div
          className="flex flex-row items-center gap-4 font-light text-neutral-700
          "
        >
          <span>{guestCount} guests</span>
          <span>{roomCount} rooms</span>
          <span>{bathroomCount} bathrooms</span>
        </div>
      </div>
      <hr />
      {category && (
        <ListingCategory
          icon={category.icon}
          label={category?.label}
          description={category?.description || ""}
        />
      )}
      <hr />
      <p className=" font-light text-neutral-500 text-[16px] ">{description}</p>
      <hr />
      <div className="h-[210px]">
      <Map center={latlng as L.LatLngExpression} />
      </div>
    </div>
  );
};

export default ListingInfo;

**Comment by sudeepmahato16** [comment]
Hi @thisismyamazingusername, it is working very well on my device. Remember to include “use client” at the beginning of the Map component like this:

"use client";

import React from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import { MapContainer, Marker, TileLayer } from "react-leaflet";
import markerIcon2x from "leaflet/dist/images/marker-icon-2x.png";
import marketIcon from "leaflet/dist/images/marker-icon.png";
import markerShadow from "leaflet/dist/images/marker-shadow.png";

// @ts-ignore
delete L.Icon.Default.prototype._getIconUrl;
L.Icon.Default.mergeOptions({
  iconUrl: marketIcon.src,
  iconRetinaUrl: markerIcon2x.src,
  shadowUrl: markerShadow.src,
});

interface MapProps {
  center?: number[];
}

const Map: React.FC<MapProps> = ({ center }) => {
  return (
    <MapContainer
      center={(center as L.LatLngExpression) || [52, -0.09]}
      zoom={center ? 4 : 2}
      scrollWheelZoom={false}
      className="h-full rounded-lg"
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      {center && <Marker position={center as L.LatLngExpression} />}
    </MapContainer>
  );
};

export default Map;

If this doesn't solve the issue, please delete the node_modules folder and install the packages again.

And to solve EdgeStoreCredentialsError, ensure you have the correct EDGE_STORE_ACCESS_KEY and EDGE_STORE_SECRET_KEY in your .env.local file.

**Comment by thisismyamazingusername** [comment]
Thank you for your support. I added "use client" and reinstalled the node_modules packages. 
However, the error still persists. I was wondering if you received this error in the past/ other projects? Maybe you added something to vercel not shown in the github? I only added my environment variables to vercel. I have also included my vercel deployment log in case there is something different than yours.

Also the goal of my project is to understand how to add "listings" to a DB for my housemates to trade items with college neighbors. studenswap.vercel.app

Attempted import error: 'DomUtil' is not exported from 'leaflet' (imported as 'DomUtil').

Import trace for requested module:
./node_modules/@react-leaflet/core/lib/dom.js
./node_modules/@react-leaflet/core/lib/index.js
./node_modules/react-leaflet/lib/hooks.js
./node_modules/react-leaflet/lib/index.js
./components/Map.tsx
./components/modals/SearchModal.tsx
./components/navbar/Search.tsx
 ⚠ ./components/Map.tsx
Attempted import error: 'leaflet' does not contain a default export (imported as 'L').

Import trace for requested module:
./components/Map.tsx
./components/modals/SearchModal.tsx
./components/navbar/Search.tsx

./components/Map.tsx
Attempted import error: 'leaflet' does not contain a default export (imported as 'L').

Import trace for requested module:
./components/Map.tsx
./components/modals/SearchModal.tsx
./components/navbar/Search.tsx


VERCEL- 

▲ Next.js 14.1.1
--
16:00:08.871 |  
16:00:09.040 | Creating an optimized production build ...
16:00:59.795 | ✓ Compiled successfully
16:00:59.796 | Linting and checking validity of types ...
16:01:05.733 | Collecting page data ...
16:01:07.971 | Generating static pages (0/9) ...
16:01:08.354 | Generating static pages (2/9)
16:01:08.355 | Generating static pages (4/9)
16:01:08.445 | Generating static pages (6/9)
16:01:08.471 | ✓ Generating static pages (9/9)
16:01:08.569 | Finalizing page optimization ...
16:01:08.569 | Collecting build traces ...
16:01:16.589 |  
16:01:16.622 | Route (app)                              Size     First Load JS
16:01:16.622 | ┌ λ /                                    1.58 kB         177 kB
16:01:16.622 | ├ λ /_not-found                          887 B          85.9 kB
16:01:16.622 | ├ λ /api/auth/[...nextauth]              0 B                0 B
16:01:16.622 | ├ λ /api/edgestore/[...edgestore]        0 B                0 B
16:01:16.623 | ├ λ /favorites                           230 B           166 kB
16:01:16.623 | ├ λ /listings/[listingId]                6.11 kB         129 kB
16:01:16.623 | ├ λ /properties                          1.58 kB         177 kB
16:01:16.623 | ├ λ /reservations                        1.58 kB         177 kB
16:01:16.623 | └ λ /trips                               1.58 kB         177 kB
16:01:16.623 | + First Load JS shared by all            85 kB
16:01:16.623 | ├ chunks/69-14efff5d5295f32f.js        29.2 kB
16:01:16.623 | ├ chunks/fd9d1056-1440a69c754c8bfc.js  53.4 kB
16:01:16.623 | └ other shared chunks (total)          2.47 kB
16:01:16.623 |  
16:01:16.623 |  
16:01:16.623 | ƒ Middleware                             75.1 kB
16:01:16.623 |  
16:01:16.623 | λ  (Dynamic)  server-rendered on demand using Node.js
16:01:16.623 |  
16:01:16.998 | Using TypeScript 5.3.3 (local user-provided)
16:01:20.435 | Build Completed in /vercel/output [1m]
16:01:20.584 | Deploying outputs...
16:01:21.016 | Injected preview comments middleware, you can disable this in your project settings.
16:01:24.387 |  
16:01:24.648 | Deployment completed
16:01:45.588 | Uploading build cache [151.66 MB]...
16:01:47.612 | Build cache uploaded: 2.024s

**Comment by sudeepmahato16** [comment]
@thisismyamazingusername Would you mind making your repo public so I can take a closer look?

**Comment by thisismyamazingusername** [comment]
Sure, the project is named ss. Thank you again!

**Comment by sudeepmahato16** [comment]
@thisismyamazingusername  I have made some changes in the repo, and it is now working well on my device. Could you please check whether it is working on your device or not?

**Comment by thisismyamazingusername** [comment]
Thank you for your changes, but I am still getting the DomUtils error... I run npm run dev and also the vercel is still showing the 404 error because of the DomUtils... Also, what is cloundinary? I have not set that up so I thought to delete the package? 

Is there any other place to potentially run it in case the error is with my computer?

**Comment by sudeepmahato16** [comment]
@thisismyamazingusername I'm sorry to hear that the issue is still happening. I couldn't figure out why it is not working on your computer but works on mine. I recommend watching this YouTube tutorial ([Watch the Video](https://youtu.be/c_-b_isI4vg?si=JxJBYQzGY9emhTZy)) and creating the project from scratch.

**Comment by thisismyamazingusername** [comment]
No worries, thank you so much for your help and sharing your project for me to learn from!
