### ISSUE TITLE
Payement button

### ISSUE THREAD

**Issue by adjebbar** [sudeepmahato16/airbnb-clone#18]
Hi,
thanks for this awesome airbnb clone. My question is about the payment module? there is no a way to finalize the paymement ?

Thanks.

**Comment by sudeepmahato16** [comment]
Hey! Thanks for reaching out! I really appreciate your feedback. The payment module isn’t set up yet, but I’ll work on it soon. If you have any other questions or suggestions, feel free to let me know!
