### ISSUE TITLE
Requesting Data from the mongoDB

### ISSUE THREAD

**Issue by amakash1** [sudeepmahato16/airbnb-clone#8]
Hey OP , I just came across this project and it’s absolutely a piece! I just hav few doubts on this.

when i try to run the project on my local system the database and the hotels never pulls up and I think it’s because my mongodb is not seeded ! Can you please let me know how to do this and also please let me know how to find the applications .env urls

**Comment by sudeepmahato16** [comment]
I created this project following the instructions from this channel ([youtu.be/c_-b_isI4vg?si=XoUVihRT5lVJGz_m](https://youtu.be/c_-b_isI4vg?si=XoUVihRT5lVJGz_m',)). Feel free to check out the channel for more details and guidance on creating the project.
